title = "Mei/Co Dance"
relativeURLs = true
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Mei/Co Dance description"
  facebook = "https://www.facebook.com/meggie.pinones"
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/mgbelisle/meico"
  linkedin = ""
  ipfs = "https://ipfs.io/ipns/meico.dance"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/hero-image.jpg"
  recent_posts_number = 3
